### PR TITLE
Adds way to get request headers

### PR DESCRIPTION
**Pull request by wpjunior**

### CODE REVIEW

**Comment by orbiteleven** [comment]
Great idea! Tests perhaps?

**Comment by jameslnewell** [comment]
Thanks for the PR!

What's the use case for this addition? It doesn't look like a standard method on the [XMLHttpRequest interface](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) and you can already check the request headers before returning a response e.g. 

```javascript
mock.get('http://localhost/api/user', function(req, res) {
  console.log(req.header('content-type'));
  return res;
});
```

**Comment by zachelrath** [comment]
@jameslnewell I agree - `MockXMLHttpRequest` should just implement the `XMLHttpRequest`, there's no practical need for this additional method.

**Comment by jameslnewell** [comment]
ping @wpjunior

**Pull request closed without merging**
